const FETCHING_DATA = 'FETCHING_DATA';
const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
const FETCHING_DATA_PEOPLE_SUCCESS = 'FETCHING_DATA_PEOPLE_SUCCESS';

export const TOGGLE_SNACKBAR_OPEN = 'TOGGLE_SNACKBAR_OPEN'; 
export const TOGGLE_SNACKBAR_CLOSE = 'TOGGLE_SNACKBAR_CLOSE'; 

export const SET_LOCALE = 'SET_LOCALE';

export const SET_URL = 'SET_URL';
export const SET_URL_SUCCESS = 'SET_URL_SUCCESS';
export const SET_URL_ERROR = 'SET_URL_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SET_AUTH_HEADER = 'SET_AUTH_HEADER';

//CLEAN ERROR

export const CLEAN_ERROR = 'CLEAN_ERROR';




