//SnackNotice
export const TOGGLE_SNACKBAR_OPEN = 'TOGGLE_SNACKBAR_OPEN'; 
export const TOGGLE_SNACKBAR_CLOSE = 'TOGGLE_SNACKBAR_CLOSE'; 
export const GET_APP_RESOURCES = 'GET_APP_RESOURCES'; 
export const SET_ERROR_APP = 'SET_ERROR_APP'; 

/* ********************************************* */ 

//LOGIN
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

//Validate Code
export const VALIDATE_CODE = 'VALIDATE_CODE';
export const VALIDATE_CODE_SUCCESS = 'VALIDATE_CODE_SUCCESS';

//Set Errors
export const SET_ERROR = 'SET_ERROR';

//CLEAN ERROR
export const CLEAN_ERROR = 'CLEAN_ERROR';
/* ********************************************* */ 

//REGISTER
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_GENDER = 'GET_GENDER';
export const GET_GENDER_SUCCESS = 'GET_GENDER_SUCCESS';
export const CLEAN_ERROR_REGISTER = 'CLEAN_ERROR_REGISTER';
export const VALIDATE_SMS = 'VALIDATE_SMS';
export const VALIDATE_SMS_SUCCESS = 'VALIDATE_SMS_SUCCESS';
export const REGISTER_PROFILE = 'REGISTER_PROFILE';
export const REGISTER_PROFILE_SUCCESS = 'REGISTER_PROFILE_SUCCESS';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';

//SAVE USER DATA
export const SAVE_DATA_USER = 'SAVE_DATA_USER';
export const CLEAN_DATA_USER = 'CLEAN_DATA_USER';

//FORGOT YOUR PASSWORD
export const FORGOT_YOUR_PASSWORD = 'FORGOT_YOUR_PASSWORD';
export const FORGOT_YOUR_PASSWORD_SUCCESS = 'FORGOT_YOUR_PASSWORD_SUCCESS';
export const FORGOT_ERROR = 'FORGOT_ERROR';
export const CLEAN_ERROR_FORGOT = 'CLEAN_ERROR_FORGOT';
export const CONFIRM_PASSWORD = 'CONFIRM_PASSWORD';
export const CONFIRM_PASSWORD_SUCCESS = 'CONFIRM_PASSWORD_SUCCESS';








