//SnackNotice
export const TOGGLE_SNACKBAR_OPEN = 'TOGGLE_SNACKBAR_OPEN'; 
export const TOGGLE_SNACKBAR_CLOSE = 'TOGGLE_SNACKBAR_CLOSE'; 
export const GET_APP_RESOURCES = 'GET_APP_RESOURCES'; 
export const SET_ERROR_APP = 'SET_ERROR_APP'; 
export const TOGGLE_STATUS_CHANGE = 'TOGGLE_STATUS_CHANGE'; 
export const TOGGLE_STATUS_CHANGE_STATUS = 'TOGGLE_STATUS_CHANGE_STATUS'; 
export const USER_ACTIVE = 'USER_ACTIVE'; 
export const USER_INACTIVE = 'USER_INACTIVE'; 

/* ********************************************* */ 

//LOGIN
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

//Validate Code
export const VALIDATE_CODE = 'VALIDATE_CODE';
export const VALIDATE_CODE_SUCCESS = 'VALIDATE_CODE_SUCCESS';

//Validate code sms
export const VALIDATE_CODE_SMS = 'VALIDATE_CODE_SMS';
export const VALIDATE_CODE_SMS_SUCCESS = 'VALIDATE_CODE_SMS_SUCCESS';
//validate email
export const VALIDATE_CODE_EMAIL = 'VALIDATE_CODE_EMAIL';
export const VALIDATE_CODE_EMAIL_SUCCESS = 'VALIDATE_CODE_EMAIL_SUCCESS';

//Set Errors
export const SET_ERROR = 'SET_ERROR';

//CLEAN ERROR
export const CLEAN_ERROR = 'CLEAN_ERROR';
/* ********************************************* */ 

//REGISTER
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_GENDER = 'GET_GENDER';
export const GET_GENDER_SUCCESS = 'GET_GENDER_SUCCESS';
export const CLEAN_ERROR_REGISTER = 'CLEAN_ERROR_REGISTER';
export const VALIDATE_SMS = 'VALIDATE_SMS';
export const VALIDATE_SMS_SUCCESS = 'VALIDATE_SMS_SUCCESS';
export const REGISTER_PROFILE = 'REGISTER_PROFILE';
export const REGISTER_PROFILE_SUCCESS = 'REGISTER_PROFILE_SUCCESS';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';


/* ********************************************* */ 

//FORGOT YOUR PASSWORD
export const FORGOT_YOUR_PASSWORD = 'FORGOT_YOUR_PASSWORD';
export const FORGOT_YOUR_PASSWORD_SUCCESS = 'FORGOT_YOUR_PASSWORD_SUCCESS';
export const FORGOT_ERROR = 'FORGOT_ERROR';
export const CLEAN_ERROR_FORGOT = 'CLEAN_ERROR_FORGOT';
export const CONFIRM_PASSWORD = 'CONFIRM_PASSWORD';
export const CONFIRM_PASSWORD_SUCCESS = 'CONFIRM_PASSWORD_SUCCESS';


/* ********************************************* */ 

//LICENSES
export const VALIDATE_CODE_LICENSES = 'VALIDATE_CODE_LICENSES';
export const VALIDATE_CODE_LICENSES_SUCCESS = 'VALIDATE_CODE_LICENSES_SUCCESS';
export const LICENSES_ERROR = 'LICENSES_ERROR';
export const CLEAN_ERROR_LICENSES = 'CLEAN_ERROR_LICENSES';
export const GET_LICENSES = 'GET_LICENSES';
export const GET_LICENSES_SUCCESS = 'GET_LICENSES_SUCCESS';
export const GET_LIST_LICENSES = 'GET_LIST_LICENSES';
export const GET_LIST_LICENSES_SUCCESS = 'GET_LIST_LICENSES_SUCCESS';
export const GET_TOTAL_LICENSES = 'GET_TOTAL_LICENSES';
export const GET_TOTAL_LICENSES_SUCCESS = 'GET_TOTAL_LICENSES_SUCCESS';
export const GET_CRYPTO_CURRENCY = 'GET_CRYPTO_CURRENCY';
export const GET_CRYPTO_CURRENCY_SUCCESS = 'GET_CRYPTO_CURRENCY_SUCCESS';
export const CURRENT_LICENSE = 'CURRENT_LICENSE';
export const CREATE_LICENSE = 'CREATE_LICENSE';
export const CREATE_LICENSE_SUCCESS = 'CREATE_LICENSE_SUCCESS';
export const GET_ADDRESS_CURRENCIES = 'GET_ADDRESS_CURRENCIES';
export const GET_ADDRESS_CURRENCIES_SUCCESS = 'GET_ADDRESS_CURRENCIES_SUCCESS';
export const GET_TOTAL_LICENSES_IN_NETWORK = 'GET_TOTAL_LICENSES_IN_NETWORK';
export const GET_TOTAL_LICENSES_IN_NETWORK_SUCCESS = 'GET_TOTAL_LICENSES_IN_NETWORK_SUCCESS';

//GET USER INFO

/* ********************************************* */ 

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const USER_ERROR = 'USER_ERROR';
export const CLEAN_DATA_USER = 'CLEAN_DATA_USER';
export const SET_FILE_URL = 'SET_FILE_URL';
export const SET_FILE_BACK = 'SET_FILE_BACK';
export const SET_FILE_FRONT = 'SET_FILE_FRONT';
export const SET_FILE_ADDRESS = 'SET_FILE_ADDRESS';
export const SET_FILE_SELFIE = 'SET_FILE_SELFIE';
export const SET_FILE_URL_SUCCESS = 'SET_FILE_URL_SUCCESS';
export const SET_FILE_FRONT_SUCCESS = 'SET_FILE_FRONT_SUCCESS';
export const SET_FILE_BACK_SUCCESS = 'SET_FILE_BACK_SUCCESS';
export const SET_FILE_ADDRESS_SUCCESS = 'SET_FILE_ADDRESS_SUCCESS';
export const SET_FILE_SELFIE_SUCCESS = 'SET_FILE_SELFIE_SUCCESS';
export const SET_FILE_URL_ERROR = 'SET_FILE_URL_ERROR';
export const CLEAN_DATA_FILE = 'CLEAN_DATA_FILE';
export const VALIDATE_SESSION= 'VALIDATE_SESSION';
export const VALIDATE_SESSION_SUCCESS= 'VALIDATE_SESSION_SUCCESS';

export const GET_TRANSACTIONS_POOL = 'GET_TRANSACTIONS_POOL';
export const GET_TRANSACTIONS_POOL_SUCCESS = 'GET_TRANSACTIONS_POOL_SUCCESS';

//REWARDS

/* ********************************************* */ 

export const VALIDATE_REWARDS_BY_USER = 'VALIDATE_REWARDS_BY_USER';
export const VALIDATE_REWARDS_BY_USER_SUCCESS = 'VALIDATE_REWARDS_BY_USER_SUCCESS';
export const CONFIG_REWARDS = 'CONFIG_REWARDS';
export const CONFIG_REWARDS_SUCCESS = 'CONFIG_REWARDS_SUCCESS';
export const VALIDATE_REWARDS_STATUS = 'VALIDATE_REWARDS_STATUS';
export const VALIDATE_REWARDS = 'VALIDATE_REWARDS';
export const VALIDATE_REWARDS_SUCCESS = 'VALIDATE_REWARDS_SUCCESS';
export const REWARDS_ERROR = 'REWARDS_ERROR';
export const CLEAN_REWARDS = 'CLEAN_REWARDS';



//POINTS

/* ********************************************* */ 

export const REWARDS_POINTS = 'REWARDS_POINTS';
export const REWARDS_POINTS_SUCCESS = 'REWARDS_POINTS_SUCCESS';
export const COMMISSION_POINTS = 'COMMISSION_POINTS';
export const COMMISSION_POINTS_SUCCESS = 'COMMISSION_POINTS_SUCCESS';
export const GATEWAY_POINTS = 'GATEWAY_POINTS';
export const GATEWAY_POINTS_SUCCESS = 'GATEWAY_POINTS_SUCCESS';
export const LIQUID_POINTS = 'LIQUID_POINTS';
export const LIQUID_POINTS_SUCCESS = 'LIQUID_POINTS_SUCCESS';
export const EXECUTES_POINTS = 'EXECUTES_POINTS';
export const EXECUTES_POINTS_SUCCESS = 'EXECUTES_POINTS_SUCCESS';
export const EXECUTES_POINTS_COMMISSION_SUCCESS = 'EXECUTES_POINTS_COMMISSION_SUCCESS';
export const SET_POINTS_GATEWAY_LIQUIDITY = 'SET_POINTS_GATEWAY_LIQUIDITY';
export const SET_POINTS_GATEWAY_LIQUIDITY_SUCCESS = 'SET_POINTS_GATEWAY_LIQUIDITY_SUCCESS';
export const SET_LIQUIDITY_POOL = 'SET_LIQUIDITY_POOL';
export const SET_LIQUIDITY_POOL_SUCCESS = 'SET_LIQUIDITY_POOL_SUCCESS';
export const SET_POINTS_UULALA_WALLET = 'SET_POINTS_UULALA_WALLET';
export const SET_POINTS_UULALA_WALLET_SUCCESS = 'SET_POINTS_UULALA_WALLET_SUCCESS';
export const POINTS_ERROR = 'POINTS_ERROR';
export const CLEAN_ERROR_POINTS = 'CLEAN_ERROR_POINTS';
export const pointsConstants = {
  POOLS: {
      TOKENS: 0,
      COMMISSION: 1,
      REWARDS: 2,
      LIQUIDITY: 3,
      GATEWAY: 4
  }
}
export const walletConstants = {
  POOLS: {
      BASE: 0,
      PENDING: 1
  }
}

//PROFILE

export const UPDATE_PROFILE_INFO = 'UPDATE_PROFILE_INFO';
export const UPDATE_PROFILE_INFO_SUCCESS = 'UPDATE_PROFILE_INFO_SUCCESS';
export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
export const EDIT_KYC = 'EDIT_KYC';
export const EDIT_KYC_SUCCESS = 'EDIT_KYC_SUCCESS';
export const CREATE_KYC = 'CREATE_KYC';
export const CREATE_KYC_SUCCESS = 'CREATE_KYC_SUCCESS';
export const CREATE_BANK_INFO = 'CREATE_BANK_INFO';
export const CREATE_BANK_INFO_SUCCESS = 'CREATE_BANK_INFO_SUCCESS';
export const EDIT_BANK_INFO = 'EDIT_BANK_INFO';
export const EDIT_BANK_INFO_SUCCESS = 'EDIT_BANK_INFO_SUCCESS';
export const TYPE_IDENTIFICATION = 'TYPE_IDENTIFICATION';
export const TYPE_IDENTIFICATION_SUCCESS = 'TYPE_IDENTIFICATION_SUCCESS';
export const UPDATE_PROFILE_AVATAR = 'UPDATE_PROFILE_AVATAR';
export const UPDATE_PROFILE_AVATAR_SUCCESS = 'UPDATE_PROFILE_AVATAR_SUCCESS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAN_ERROR_PROFILE = 'CLEAN_ERROR_PROFILE';

